---
- name: Compose SEMPv2 request payload for RDP Endpoint "{{ rdp.restDeliveryPointName }}"
  template: src=templates/rdp.json.j2 dest=files/rdp.json

- name: Create RDP Endpoint "{{ rdp.restDeliveryPointName }}"
  uri:
   url: "https://{{ mgmt_host }}:{{ mgmt_port }}/SEMP/v2/config/msgVpns/{{ vpn }}/restDeliveryPoints"
   method: POST
   user: "{{ semp_username}}"
   password: "{{ semp_password }}"
   headers:
    Content-Type: "application/json"
   body: '{{ lookup("file","files/rdp.json") }}'
   body_format: json
   force_basic_auth: yes
   status_code: 200
   return_content: yes
  register: result
  ignore_errors: True
  retries: 3
  delay: 1
  when: rdp.action == 'POST'

- name: Error in RDP Endpoint creation?
  debug:
   var: result.json.meta.error.status
  when: (result.json.meta.responseCode is undefined or result.json.meta.responseCode != 200) and rdp.action == 'POST'
  
- name: Update RDP Endpoint "{{ rdp.restDeliveryPointName }}"
  uri:
   url: "https://{{ mgmt_host }}:{{ mgmt_port }}/SEMP/v2/config/msgVpns/{{ vpn }}/restDeliveryPoints/{{ rdp.restDeliveryPointName }}"
   method: PATCH
   user: "{{ semp_username}}"
   password: "{{ semp_password }}"
   headers:
    Content-Type: "application/json"
   body: '{{ lookup("file","files/rdp.json") }}'
   body_format: json
   force_basic_auth: yes
   status_code: 200
   return_content: yes
  register: result
  ignore_errors: True
  retries: 3
  delay: 1
  when: rdp.action == 'PATCH'

- name: Error in RDP Endpoint update?
  debug:
   var: result.json.meta.error.status
  when: (result.json.meta.responseCode is undefined or result.json.meta.responseCode != 200) and rdp.action == 'PATCH'  
  
- name: Delete RDP Endpoint "{{ rdp.restDeliveryPointName }}"
  uri:
   url: "https://{{ mgmt_host }}:{{ mgmt_port }}/SEMP/v2/config/msgVpns/{{ vpn }}/restDeliveryPoints/{{ rdp.restDeliveryPointName }}"
   method: DELETE
   user: "{{ semp_username}}"
   password: "{{ semp_password }}"
   force_basic_auth: yes
   status_code: 200
   return_content: yes
  register: result
  ignore_errors: True
  retries: 3
  delay: 1
  when: rdp.action == 'DELETE'

- name: Error in RDP Endpoint deletion?
  debug:
   var: result.json.meta.error.status
  when: (result.json.meta.responseCode is undefined or result.json.meta.responseCode != 200) and rdp.action == 'DELETE'    
